'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5444
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.5444.
'
Namespace PAFSocial
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="SocialConnection.cfcSoapBinding", [Namespace]:="http://DefaultNamespace"),  _
     System.Xml.Serialization.SoapIncludeAttribute(GetType(QueryBean)),  _
     System.Xml.Serialization.SoapIncludeAttribute(GetType(CFCInvocationException)),  _
     System.Xml.Serialization.SoapIncludeAttribute(GetType(Map))>  _
    Partial Public Class SocialConnection
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private GetFriendsOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetFriendCountOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetLocationURLOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetLocationOperationCompleted As System.Threading.SendOrPostCallback
        
        Private SetLocationURLOperationCompleted As System.Threading.SendOrPostCallback
        
        Private SetLocationOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetActivityOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.PrefinitiBrowser.My.MySettings.Default.PrefinitiBrowser_PAFSocial_SocialConnection
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event GetFriendsCompleted As GetFriendsCompletedEventHandler
        
        '''<remarks/>
        Public Event GetFriendCountCompleted As GetFriendCountCompletedEventHandler
        
        '''<remarks/>
        Public Event GetLocationURLCompleted As GetLocationURLCompletedEventHandler
        
        '''<remarks/>
        Public Event GetLocationCompleted As GetLocationCompletedEventHandler
        
        '''<remarks/>
        Public Event SetLocationURLCompleted As SetLocationURLCompletedEventHandler
        
        '''<remarks/>
        Public Event SetLocationCompleted As SetLocationCompletedEventHandler
        
        '''<remarks/>
        Public Event GetActivityCompleted As GetActivityCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace:="http://DefaultNamespace", ResponseNamespace:="http://DefaultNamespace")>  _
        Public Function GetFriends(ByVal username As String) As <System.Xml.Serialization.SoapElementAttribute("GetFriendsReturn")> Object()
            Dim results() As Object = Me.Invoke("GetFriends", New Object() {username})
            Return CType(results(0),Object())
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetFriendsAsync(ByVal username As String)
            Me.GetFriendsAsync(username, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetFriendsAsync(ByVal username As String, ByVal userState As Object)
            If (Me.GetFriendsOperationCompleted Is Nothing) Then
                Me.GetFriendsOperationCompleted = AddressOf Me.OnGetFriendsOperationCompleted
            End If
            Me.InvokeAsync("GetFriends", New Object() {username}, Me.GetFriendsOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetFriendsOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetFriendsCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetFriendsCompleted(Me, New GetFriendsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace:="http://DefaultNamespace", ResponseNamespace:="http://DefaultNamespace")>  _
        Public Function GetFriendCount(ByVal username As String) As <System.Xml.Serialization.SoapElementAttribute("GetFriendCountReturn")> Double
            Dim results() As Object = Me.Invoke("GetFriendCount", New Object() {username})
            Return CType(results(0),Double)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetFriendCountAsync(ByVal username As String)
            Me.GetFriendCountAsync(username, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetFriendCountAsync(ByVal username As String, ByVal userState As Object)
            If (Me.GetFriendCountOperationCompleted Is Nothing) Then
                Me.GetFriendCountOperationCompleted = AddressOf Me.OnGetFriendCountOperationCompleted
            End If
            Me.InvokeAsync("GetFriendCount", New Object() {username}, Me.GetFriendCountOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetFriendCountOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetFriendCountCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetFriendCountCompleted(Me, New GetFriendCountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace:="http://DefaultNamespace", ResponseNamespace:="http://DefaultNamespace")>  _
        Public Function GetLocationURL(ByVal username As String) As <System.Xml.Serialization.SoapElementAttribute("GetLocationURLReturn")> String
            Dim results() As Object = Me.Invoke("GetLocationURL", New Object() {username})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetLocationURLAsync(ByVal username As String)
            Me.GetLocationURLAsync(username, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetLocationURLAsync(ByVal username As String, ByVal userState As Object)
            If (Me.GetLocationURLOperationCompleted Is Nothing) Then
                Me.GetLocationURLOperationCompleted = AddressOf Me.OnGetLocationURLOperationCompleted
            End If
            Me.InvokeAsync("GetLocationURL", New Object() {username}, Me.GetLocationURLOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetLocationURLOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetLocationURLCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetLocationURLCompleted(Me, New GetLocationURLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace:="http://DefaultNamespace", ResponseNamespace:="http://DefaultNamespace")>  _
        Public Function GetLocation(ByVal username As String) As <System.Xml.Serialization.SoapElementAttribute("GetLocationReturn")> String
            Dim results() As Object = Me.Invoke("GetLocation", New Object() {username})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetLocationAsync(ByVal username As String)
            Me.GetLocationAsync(username, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetLocationAsync(ByVal username As String, ByVal userState As Object)
            If (Me.GetLocationOperationCompleted Is Nothing) Then
                Me.GetLocationOperationCompleted = AddressOf Me.OnGetLocationOperationCompleted
            End If
            Me.InvokeAsync("GetLocation", New Object() {username}, Me.GetLocationOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetLocationOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetLocationCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetLocationCompleted(Me, New GetLocationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace:="http://DefaultNamespace", ResponseNamespace:="http://DefaultNamespace")>  _
        Public Sub SetLocationURL(ByVal username As String, ByVal location_url As String)
            Me.Invoke("SetLocationURL", New Object() {username, location_url})
        End Sub
        
        '''<remarks/>
        Public Overloads Sub SetLocationURLAsync(ByVal username As String, ByVal location_url As String)
            Me.SetLocationURLAsync(username, location_url, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub SetLocationURLAsync(ByVal username As String, ByVal location_url As String, ByVal userState As Object)
            If (Me.SetLocationURLOperationCompleted Is Nothing) Then
                Me.SetLocationURLOperationCompleted = AddressOf Me.OnSetLocationURLOperationCompleted
            End If
            Me.InvokeAsync("SetLocationURL", New Object() {username, location_url}, Me.SetLocationURLOperationCompleted, userState)
        End Sub
        
        Private Sub OnSetLocationURLOperationCompleted(ByVal arg As Object)
            If (Not (Me.SetLocationURLCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent SetLocationURLCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace:="http://DefaultNamespace", ResponseNamespace:="http://DefaultNamespace")>  _
        Public Sub SetLocation(ByVal username As String, ByVal location As String, ByVal activity As String)
            Me.Invoke("SetLocation", New Object() {username, location, activity})
        End Sub
        
        '''<remarks/>
        Public Overloads Sub SetLocationAsync(ByVal username As String, ByVal location As String, ByVal activity As String)
            Me.SetLocationAsync(username, location, activity, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub SetLocationAsync(ByVal username As String, ByVal location As String, ByVal activity As String, ByVal userState As Object)
            If (Me.SetLocationOperationCompleted Is Nothing) Then
                Me.SetLocationOperationCompleted = AddressOf Me.OnSetLocationOperationCompleted
            End If
            Me.InvokeAsync("SetLocation", New Object() {username, location, activity}, Me.SetLocationOperationCompleted, userState)
        End Sub
        
        Private Sub OnSetLocationOperationCompleted(ByVal arg As Object)
            If (Not (Me.SetLocationCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent SetLocationCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace:="http://DefaultNamespace", ResponseNamespace:="http://DefaultNamespace")>  _
        Public Function GetActivity(ByVal username As String) As <System.Xml.Serialization.SoapElementAttribute("GetActivityReturn")> String
            Dim results() As Object = Me.Invoke("GetActivity", New Object() {username})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetActivityAsync(ByVal username As String)
            Me.GetActivityAsync(username, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetActivityAsync(ByVal username As String, ByVal userState As Object)
            If (Me.GetActivityOperationCompleted Is Nothing) Then
                Me.GetActivityOperationCompleted = AddressOf Me.OnGetActivityOperationCompleted
            End If
            Me.InvokeAsync("GetActivity", New Object() {username}, Me.GetActivityOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetActivityOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetActivityCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetActivityCompleted(Me, New GetActivityCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="http://rpc.xml.coldfusion")>  _
    Partial Public Class QueryBean
        
        Private columnListField() As String
        
        Private dataField() As Object
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property columnList() As String()
            Get
                Return Me.columnListField
            End Get
            Set
                Me.columnListField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property data() As Object()
            Get
                Return Me.dataField
            End Get
            Set
                Me.dataField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="http://rpc.xml.coldfusion")>  _
    Partial Public Class CFCInvocationException
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="http://xml.apache.org/xml-soap")>  _
    Partial Public Class Map
        
        Private itemField() As mapItem
        
        '''<remarks/>
        Public Property item() As mapItem()
            Get
                Return Me.itemField
            End Get
            Set
                Me.itemField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="http://xml.apache.org/xml-soap")>  _
    Partial Public Class mapItem
        
        Private keyField As Object
        
        Private valueField As Object
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property key() As Object
            Get
                Return Me.keyField
            End Get
            Set
                Me.keyField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property value() As Object
            Get
                Return Me.valueField
            End Get
            Set
                Me.valueField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")>  _
    Public Delegate Sub GetFriendsCompletedEventHandler(ByVal sender As Object, ByVal e As GetFriendsCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetFriendsCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Object()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Object())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")>  _
    Public Delegate Sub GetFriendCountCompletedEventHandler(ByVal sender As Object, ByVal e As GetFriendCountCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetFriendCountCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Double
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Double)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")>  _
    Public Delegate Sub GetLocationURLCompletedEventHandler(ByVal sender As Object, ByVal e As GetLocationURLCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetLocationURLCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")>  _
    Public Delegate Sub GetLocationCompletedEventHandler(ByVal sender As Object, ByVal e As GetLocationCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetLocationCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")>  _
    Public Delegate Sub SetLocationURLCompletedEventHandler(ByVal sender As Object, ByVal e As System.ComponentModel.AsyncCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")>  _
    Public Delegate Sub SetLocationCompletedEventHandler(ByVal sender As Object, ByVal e As System.ComponentModel.AsyncCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")>  _
    Public Delegate Sub GetActivityCompletedEventHandler(ByVal sender As Object, ByVal e As GetActivityCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetActivityCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
End Namespace
